# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: lr-gatk-alpha
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  #- conda-forge::openjdk # Needed for FastQC docker - see bioconda/bioconda-recipes#5026
  #- bwa=0.7.17
  #- samtools=1.9
  #- multiqc=1.6
  #- fastqc=0.11.7
  #- gatk4=4.1.0.0
  - bioconda::qualimap=2.2.2a
  - bioconda::nextflow=19.04.0
