# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: lr-gatk-alpha
channels:
  # To speed up things ("solving environment"), only specify necessary channels.
  # I've specified the channels I've found to be the fastest for the different packages.
  - bioconda
  - conda-forge
  #- compbiocore
  #- defaults

dependencies:
  # Again, to speed things up, specify channel and version.
  - bioconda::fastqc=0.11.7
  - bioconda::gatk4=4.1.0.0
  - bioconda::qualimap=2.2.2a
  - bioconda::nextflow=19.04.0
  - bioconda::snpeff=4.3.1t
  - bioconda::multiqc=1.7
  - bioconda::bcftools=1.9
  - bioconda::whatshap=0.18
  - bioconda::tabix=0.2.6
  - bioconda::perl-vcftools-vcf=0.1.16
  - conda-forge::r-gsalib=2.1
  - conda-forge::r-gplots=3.0.1.1
  - conda-forge::r-ggplot2=3.1.1
