
name: exolink-alpha

channels:
  - bioconda
  - conda-forge
  - Freenome
  - AgBiome

dependencies:
  - Freenome::bcl2fastq=2.20
  - bioconda::fastqc=0.11.8
  - bioconda::ema=0.6.2
  - bioconda::gatk4=4.1.0.0
  - bioconda::qualimap=2.2.2a
  - bioconda::nextflow=19.04.0
  - bioconda::snpeff=4.3.1t
  - bioconda::multiqc=1.7
  - bioconda::bcftools=1.9
  - bioconda::whatshap=0.18
  - bioconda::tabix=0.2.6
  - bioconda::samtools=1.9
  - bioconda::bwa=0.7.17
  - bioconda::perl-vcftools-vcf=0.1.16
  - AgBiome::bbtools=37.62
  - bioconda::fastp=0.20.0
  - bioconda::sickle-trim::1.33
  - conda-forge::r-gsalib=2.1
  - conda-forge::r-gplots=3.0.1.1
  - conda-forge::r-ggplot2=3.1.1
